### ISSUE TITLE
Add an option for a black & white icon in the OS X header

### ISSUE THREAD

**Issue by andersius** [TermiT/Flycut#107]
Having all other apps / icons in the OSX system header being black, it would look much better without the Flycut red icon. If you would like any help with this, just send me the logo files, and I can fix it for you ;-)

**Comment by MarkJerde** [comment]
This has been in there for a long time already. You can browse/search the other issues to see when it was added. If you are using the App Store version that hasn't been updated since 2010 or 2011 you will, of course, be missing most features.

It's in the preferences (accessed from the Flycut menu). On the Appearances pane, I think.
