### ISSUE TITLE
Add a new field

### ISSUE THREAD

**Issue by tiaruom** [TermiT/Flycut#11]
I have always use jumpcut but I'm now trying your version. I suggest something to jumpcut but I had no returns. Perhaps could you listen to my suggestion.
I have to paste same texte (several in fact) throughout the day in case of my work. I think I could save my time if there are a part of flycut where I could define my own text independently of the clipboard. I will consequently paste some text with another shortcut than the principal one. That second clipboard will not be modified when I copy a new text like that I know that the text "exemple" is in the 13 position and I'he just to apperal this 13 position to copy the good text.
I wish I was clear in my explication. I apologze for my bad english, I'm a french user.
Thanks,
Cordially,
Jean Baptiste

**Comment by NickHibma** [comment]
Sort of a 'Star' or 'Favorite' icon on the bezel? That would indeed be handy.

**Comment by MarkJerde** [comment]
This was actually added quite a few years ago. Tap the ‘f’ key in the bezel you switch between Main and Favorites lists. Use ‘Shift-f’ to move the current item between the two lists. I think if you switch to the Favorites list and then esc out new clippings will be placed on that list until you switch it back. 

Standard disclaimer that none of this is in the App Store version (1.5) because that is close to a decade old since the API used for pasting is no longer allowed on the App Store. 

Hope this helps,
Mark

**Comment by NickHibma** [comment]
Mark,

Thanks for the update. I hadn't noticed the fact that there were two versions.

The github version is much better. Thanks.

Nick Hibma
nick@van-laarhoven.org

-- Open Source: We stand on the shoulders of giants.
