### ISSUE TITLE
NSStringPboardType instead of ClipboardEntry

### ISSUE THREAD

**Issue by TheRojam** [TermiT/Flycut#116]
```
Given Flycut (Version 1.8 (1.82f0187.35.1604)
 And $ClipboardEntry
When I want to paste my $ClipboardEntry
Then sometimes "NSStringPboardType" is pasted instead of $ClipboardEntry
 But my $ClipboardEntry is in the history of Flycut
```

Even while writing this issue comes up.
So what can I do? what need I todo?!
What do you need as **information** as i can serve?

**Comment by MarkJerde** [comment]
This deserves an award for the best bug report ever. The Flycut version number and clear description are so helpful. The first thing that comes to mind is an option I put into the settings in the password avoidance stuff to include the clipping type when copying, so the user can know what to put in that field to avoid specific types. Is that setting turned on?

Otherwise that's pretty weird, and almost like that feature is operating when it shouldn't. If you look at your Flycut history, do you have one of these for each actual clipping or is it a subset? If it's a subset is there any pattern of which apps it happens or doesn't happen with? What OS are you using?

Thanks!
Mark

**Comment by TheRojam** [comment]
@MarkJerde first & second sentence is joke isn't it? seems sarcastic or ironic?!

**Comment by MarkJerde** [comment]
@TheRojam - Not at all. The number of times I've had to practically beat any description of what Flycut version they are using and how and what they are encountering is exhausting. I am actually so thrilled to see a bug report that is clear and precise. Thank you. (And I implemented that version number system so I'm glad to see it put to use. And even know at a glance that you are running a build from April of this year.)

**Comment by MarkJerde** [comment]
Er, "had to practically beat out of people any description..."

**Comment by TheRojam** [comment]
@MarkJerde 
_So what do you mean with_
> The first thing that comes to mind is an option I put into the settings in the password avoidance stuff to include the clipping type when copying, so the user can know what to put in that field to avoid specific types. Is that setting turned on?
_?_

![FlyCut Prefferences](https://cloud.githubusercontent.com/assets/1362428/18291242/223cdda8-7487-11e6-846e-b3c28cacc502.png)

_My OS is_ El Capitan v. 10.11.6 (15G1004)

**Comment by MarkJerde** [comment]
"Include pasteboard types in clippings list". You have it checked, which is why those are in your clippings. Uncheck it.

**Comment by TheRojam** [comment]
👍  thanks a lot :)

**Comment by TheRojam** [comment]
> I am actually so thrilled to see a bug report that is clear and precise. 

I had to writing feature-files for [cucumber](https://cucumber.io/docs#reference) ui tests and its so easy to use it for issues - i am even do it at work

**Comment by TheRojam** [comment]
Bug didn't appeared again. Due this i close this issue.  @MarkJerde thank you for your help!
