### ISSUE TITLE
[Enhancement] Implement LRU ordering for pastes

### ISSUE THREAD

**Issue by brailsmt** [TermiT/Flycut#123]
I use my clipboard a lot.  I use it for working all the myriads of credentials (not overly worried about security with these), IPs, hostname, etc... that I need while at work.  The problem I'm seeing is that I copy/paste so much, the most frequently used pastes fall off the 100 paste buffer several times a day.  I would really prefer a buffer aging system that was not strictly FIFO.  An option to remove the Least Recently Used (LRU) pastes would be vastly more user friendly for me.  The frequent servers and credentials I use would stay in the list of pastes, whereas code snippets would quickly fall off.  I envision something such as enhancing each paste with a timestamp of the last time it was selected, and then listing the pastes in in descending order of the timestamp.  This would keep frequently used pastes near the top.

**Comment by MarkJerde** [comment]
Hi brailsmt,
It already is an LRU if you have Flycut's preferences set to move selected clippings to top. 

Beyond that, I'm pretty sure it's impossible for Flycut to know when you Cmd-v paste, since the OS doesn't advertise that. But that would always be the most-recently pasted or freshly copied so that may be irrelevant. 

I was working on a feature concept (mentioned in another issue here) to score clippings based on their depth in the clippings list (e.g. If you select clipping #25 it has 25 added to its score) and then remove the least recently used item with a zero score, decrementing the score of each that was skipped over for removal. My testing didn't show much benefit, though. Perhaps an auto-tuned scoring would help. 

Hope this helps,
Mark

**Comment by brailsmt** [comment]
I do not see a preference option for moving selected clippings to the top.

**Comment by brailsmt** [comment]
nm, I had the AppStore version.  I switched to the HomeBrew version and I can see the option now.  Thanks.  That feature resolves this enhancement.
