### ISSUE TITLE
Rearrange clipboard with recently used at top.

### ISSUE THREAD

**Issue by harshakokel** [TermiT/Flycut#139]
Hello,
Is there a provision to rearrange the clipboards based on recently pasted text. I see it is sorted only by the recently copied text.

**Comment by MarkJerde** [comment]
Hi harshakokel,
It's in the preferences somewhere. Sorry I don't have my Mac handy at the moment. Something like "Paste moves to top". I'm not sure if this is in the App Store version, since that is from 2011. Let me know if you can't find it and I'll reply again when I'm at my computer. 
Best regards,
Mark

**Comment by harshakokel** [comment]
Thanks Mark, I downloaded the DRM version and was able to find the option. Thank you. 
Also, while I am here. This app is very useful thank you for keeping it open source.

regards,
Harsha.
