### ISSUE TITLE
Help Understanding Preferences Options

### ISSUE THREAD

**Issue by syberknight** [TermiT/Flycut#141]
love Flycut! but there's a couple things in the Preferences that I don't understand what they are nor how I should have them set...

1) Pasteboard Types (default is checked & has "PasswordPboardType" in the field.

2) Save forgotten items to Desktop -Clippings & -Favorites.

much appreciated, & thanks for making this app!

**Comment by MarkJerde** [comment]
Hi syberknight,

1. "Pasteboard types:" is a child of (indented below) "Don't copy from password fields".  It specifies an indicator of pasteboard items that should not be remembered.  In deep detail, the Mac pasteboard keeps one or more different versions of each clipping in a look-up table keyed by various "types".  These versions could be things like "rich text", "plain text", "image" (if it were an image).  So you can copy an image and then paste it somewhere that only text make sense and you will get the filename.  So the feature looks for (by default) PasswordPboardType which was used by some random password wallet many many years ago.  I haven't done the code archeology on it, but I think this feature doesn't even work anymore since it filters the available types down to only NSStringPboardType before checking.

2. Flycut has a limited number of clippings that it will remember.  At the time they will be forgotten, this feature saves them to files on the Desktop modeled after the way in which the macOS screen shot capability saves the screen shots to files on the Desktop.  There are options for Clippings and Favorites because Flycut has two stores and granularity in selection allows a user to say that they want to be sure not to lose items from the favorites but are okay losing them from the primary ("clippings") store.

Hope this helps,
Mark

**Comment by syberknight** [comment]
ah. thank you :-)
