### ISSUE TITLE
Ability to write functions to parse clipboard contents

### ISSUE THREAD

**Issue by davidawad** [TermiT/Flycut#148]
it would be really cool if i could write programs or hooks that would be called upon something being copied/ pasted and added to my clipboard. 

How feasible is this?
let me know what you think! Thanks!

**Comment by shaleh** [comment]
What are some use cases?

**Comment by InnovativeInventor** [comment]
A possible example might be a program to open up an email app when an email address is added to the clipboard. I agree that it would be very cool and would open up many possibilities if this were possible.

**Comment by InnovativeInventor** [comment]
Good point, although allowing users to create their own custom programs doesn't sound like feature creep to me. Users can then choose what they want to add to Flycut and increase their productivity that way, although pbpaste/pbcopy sounds like a great way to work around this. 

@davidawad I think there are some python modules out there that help you manipulate the clipboard. I would love to see any of the things you come up with!

**Comment by MarkJerde** [comment]
I'm glad that helped, @davidawad.  Now if only we could have a Flycut command-line utility, so `fcpaste|sed "s/^+//"|fccopy` would paste whatever is at the current Flycut stack position (since the bezel can be closed and reopened at any position in the list), modify it, and then replace the content of that stack position with the modified form.  :-)
