### ISSUE TITLE
Suggestion: Regex replace

### ISSUE THREAD

**Issue by Felixrising** [TermiT/Flycut#153]
Suggestion (couldn't see whether it's been suggested earlier). 

Definitely need to add some regex replace magic to Flycut. This would make it super powerful!

**Comment by MarkJerde** [comment]
Hi @Felixrising,
This is pretty much the same thing as #148.  The tl;dr is that I've thought about adding regex for years but refrained because it seems like feature creep.  Instead of making Flycut more complicated, I accomplish this via aliases on the command line.

> Here is one I've been making good use of:
> `alias pbpatchclean='pbpaste|sed "s/^+//"|pbcopy`
> Which just strips out the leading "+" sign in patch files, so I can copy a section of new and existing lines of code out of a patch, clean it up, and paste it into an editor.  Saves having to clean it up manually.

Of course, there are scenarios where it could be awesome and more powerful to have such things integrated, so I'm not forever opposed to such ideas.  It just needs to be truly valuable being integrated rather than tangentially related stuff bolted on.

One case I've imagined is if there were a series of regex transformations on a clipping that may be desired, so in the bezel the user could just tap "x" and see the displayed content change until they got to the transformation they wanted, and then press return to paste (probably keeping the original form in the flycut store).  A more elaborate similar idea could be a set of regex rule/transformation pairs, where any clipping would be evaluated against the rule regex, and if it were successful would make available the transformation regex.  In the bezel, the user could type "rN", where "N" is a regex number (out of the available ones per the rules) and the corresponding transformed clipping would be displayed.  "r0" would return to the original clipping.  Transformations would only be on the original content, not cumulative, though the user could type "R" to put the current transformed state atop the flycut store and continue, or "Option-R" to replace the original clipping with the transformed state.

Enough concept rambling for now.  Hope this helps.  Sorry it took a couple days to remember to respond.
- Mark
