### ISSUE TITLE
Choose location to save clippings and be able to view saved clippings

### ISSUE THREAD

**Issue by jeffreymeng** [TermiT/Flycut#154]
It would be really, really useful to be able to choose the location where you store the clippings(like a folder in documents), and to be able to have an interface let you read them easily.

**Comment by MarkJerde** [comment]
I implemented that feature and completely agree with you.  The rationale behind going to the Desktop is just that it was mimicking what the macOS screen capture does.  I disable desktop icons on all my Mac systems, so it doesn't bother me, but the autosave clippings would have to be unbearable to anybody who uses desktop icons.  Looks like screen capture destination can be changed via the command line, but I suppose we should do better than that.  :-)  I'll take a look at this if I find time.

Would Finder / QuickLook be a good enough interface for easily viewing them if the user had configured for them to go to a dedicated clippings folder?  Could do searching on that folder via Finder and could press the space bar in Finder to preview any of them in QuickLook?

Thanks,
Mark

**Comment by knyttl** [comment]
Where can I see this feature? I cannot find "clippings folder"

**Comment by ptoche** [comment]
Same question. I just found 1,500 clippings on my desktop.

**Comment by knyttl** [comment]
> Same question. I just found 1,500 clippings on my desktop.

This happens to me all the time :/ It would be better to just concat them to some existing file with clip history

**Comment by CyKiK** [comment]
Same issue here. I have a ton of "Autosave Clipping XXXX-XX-XX at XX.XX.XX" files on my desktop. On my Mojave computer it is less of a big deal since they automatically go into neat folders but on my older OS computer its a mess. Of course with an update, comes OS compatibility issues anyway so I imagine this isn't likely to be fixed for my scenario. Overall Flycut is an amazing tool. Been using it for years. Apple should pay you to help implement it in the OS by default. Thank you for making it.
