### ISSUE TITLE
Pasting function is broken in macOS Majove

### ISSUE THREAD

**Issue by boqian2000** [TermiT/Flycut#156]
After copying the strings are saved in the system, but when I try to paste the string nothing happens.

**Comment by coursrock** [comment]
Yes, when I copy, Flycut capture the string, and when I try to paste, I see the copied string in the Flycut bezel and can key through all the copied strings, but when I finally release cmd+shft to paste the selected string, nothing is actually pasted to the target.  This happens regardless of the target application.

I noticed, the first time I tried to paste with Flycut after updating to Mojave, that focus switched to System Preferences, but System Preferences was in a "not responding" state (because of a problem with Time Machine settings), so I wonder if Flycut was trying to set up a third-party extension in System Preferences or perhaps gain access to accessibility controls, and failed to do so because System Preferences was not responding.

**Comment by MarkJerde** [comment]
Did you give Flycut access in System Preferences -> Security & Privacy -> Privacy -> Accesibility?

**Comment by MarkJerde** [comment]
So Flycut works successfully on Mojave? (Just to confirm.)

You guys lucked out that boqian2000’s message came in just as I was walking to the Apple store, so I had a handy test system. :-D

**Comment by coursrock** [comment]
Yes, that works.  Thanks so much, Mark.  I figured it was a System Preference thing, but I just wasn't looking in the right place.

**Comment by andreasimner** [comment]
Flycut (downloaded from App Store) was working for me in Mojave but then it stopped working as described in the original post
I tried to do this

> Did you give Flycut access in System Preferences -> Security & Privacy -> Privacy -> Accesibility?

but I am not able to add or drag/drop Flycut in to that box. 
However, I did find Flycut in the System Preferences -> Security & Privacy -> Privacy -> Automation but that doesn't solve the problem either...

**Comment by jaumebalust** [comment]
I created a PR so that the information provided by @MarkJerde  is shown on the readme 
#163

**Comment by ezquerzelaya** [comment]
I love your work, Mark. I will be making a modest donation.
