### ISSUE TITLE
Permanent Save to Flycut

### ISSUE THREAD

**Issue by nelgster** [TermiT/Flycut#158]
I have Flycut set to remember 99 clips but after 100 it starts erasing clips. I have certain clips that I use frequently and it would be nice if there was a permanent memory for say 10 clips or so that could always be accessed and pasted. that way I wouldn't have to open up notes and copy the snippet to Flycut again.

**Comment by MarkJerde** [comment]
Hi @nelgster. From the bezel, just press F (shift key and F key together) to move the currently displayed clipping to the Favorites list. Then use f (just the F key) to switch to the Favorites list and the same key to switch back. The Favorites list uses a yellow background on the bezel so you can tell which one you are in. 

Hope this helps,
Mark

**Comment by nelgster** [comment]
I tried this however when i press shift and F it goes to a copied text that starts with F. when i press F key by itself it does not change to the Favorites list. It also goes to copied text that starts with F.

**Comment by MarkJerde** [comment]
@nelgster Interesting. Is this through the menu or through the bezel? What version of Flycut are you using? I think that’s found in the Flycut preferences panel. (I’m on mobile right now so can’t check.)

**Comment by nelgster** [comment]
I'm on version 1.5. i'm not sure what the bezel is. but what i was doing was clicking on the flycut icon in the top bar and the menu opens, i hover over the text and press shift F. assuming that i'm doing it wrong.

**Comment by MarkJerde** [comment]
I think 1.5 is the App Store version. That hasn't been updated since something like 2011, and cannot be updated now because the API used to synthesize Command-V to make a paste actually happen is an API that Apple no longer allows on the App Store. You can find a current version here: https://github.com/TermiT/Flycut/releases

The App Store version is good to keep available to on the App Store as a way for people to find Flycut, but at this point is missing a lot of great features.

What you're seeing is probably just normal menu handling that typing a key with any menu open will move to an item that begins with that letter. The bezel is what appears in the middle of the screen when you press Shift-Command-V, allowing you to see each clipping in more detail than can fit in the menu, and beyond just the most recent ten.

**Comment by nelgster** [comment]
ok great! i got it now. thanks for all your help!
