### ISSUE TITLE
Security Suggestion: Use Secure Keyboard Input

### ISSUE THREAD

**Issue by hitsfromdabong** [TermiT/Flycut#165]
I'm just wondering whether this nice utility might be lowering the guards on security and what could be done about it.

It is common practice to copy and paste passwords. Thus having a history of clipboards certainly raises an issue here.

How secure is the default macOS clipboard?

Does Flycut use the same mechanism?

Might add an option to enable Secure Keyboard Input? Or add extra functionality for password type clipboards?
[Link to awesome Stack Overflow post on Secure Keyboard Input](https://security.stackexchange.com/questions/47749/how-secure-is-secure-keyboard-entry-in-mac-os-xs-terminal/47786#47786)

**Comment by MarkJerde** [comment]
The macOS pasteboard provides no security. Apps containing sensitive content may prevent content from being copied, such as in a password field where the password is not actually displayed, but once content has been copied there are no security systems in play beyond user-account level security. 

Flycut provides three mechanisms for preventing observation and storing of passwords. Those are a configurable filter based on pasteboard content types which may be provided by applications which provide content which is copied (such as KeyPassX, a password wallet that intentionally places passwords on the pasteboard, which includes a pasteboard type to indicate sensitivity); a configurable filter on clipping length and content to detect and ignore likely passwords; and an easy ability to turn pasteboard observation on and off by control-clicking that Flycut menu item. A suggestion was made here to filter by source application, but as that information is not stored On the pasteboard it would be prone to false-negatives and thus a bad idea to provide security that silently fails. 

Flycut does not provide a pasteboard, but merely interacts with the system pasteboard in the same way that any application can. To that end, it does not use the same mechanism as the system pasteboard but it interacts with the actual system pasteboard through documented APIs. 

With respect to Secure Keyboard Input, that deals with the observation of keystrokes. Flycut does not use any keystroke observation to obtain clippings, only observes keystrokes to the extent that it has registers a hot key (not actual keystroke observation since it is a notification in response to the system’s observation) and that it observes keypresses while its NSPanel is focused and receiving input. The only keystroke that Flycut synthesizes is Command-v to cause the system to observe a paste hotkey, and as such no observably-interesting keystrokes are generated. 

Hope this helps,
Mark
