### ISSUE TITLE
Mojave Compatibility?

### ISSUE THREAD

**Issue by syberknight** [TermiT/Flycut#168]
am ready to finally upgrade Mac OS to 10.14 Mojave, but am first wanting to know if Flycut 1.8.2 is compatible or not. 

i've been using Flycut for years and IMHO it's quite simply the best clipboard app. i'd like to not loose it if possible.

is this still being developed/maintained? if not, can somebody suggest an alternative that works similarly, by having clipboard items viewable/useable/pasteable via the menubar?
thanks.

**Comment by MarkJerde** [comment]
I'm a Flycut developer and I used Flycut on two Mojave systems without any problems. Even the "open on login" works fine. I installed my new Mojave system from Flycut 1.9.2 here: https://github.com/MarkJerde/Flycut/releases

- Mark

**Comment by syberknight** [comment]
hi Mark,

thank you for this!!!

i see that this is considered a "fork" - i'm not quite sure what that means & why it seems to be under your account instead of the main flycut one. why wouldn't this version be as an update to the official app? (no disrespect, just trying to understand).

i've gone ahead & downloaded/installed your version. i'll probably upgrade to Mojave later this week.
-jason.

**Comment by MarkJerde** [comment]
Hi Jason,
It's just under my account (still) because I've been too shy to Pull Request something like 50 or 60 commits all in one big lump. I need to get over it and just create the Pull Request already. There was a lot of work that went into creating an iOS port, adding iCloud sync, and cleaning up a bunch of older Flycut code that was merely getting away with running on the wrong threads and run loops. I tried to polish and combine the commits as much as appropriate, and at this point they are pretty well refined.

My latest build is the best Flycut build to use at this point, because it includes fixes like updates to the menu or bezel if you copy and then open one of them quickly. Without these changes the UI won't update when a new clipping is detected while open. It's an annoyance I put up with for many years, but now is fixed. It's also the best Flycut build because I'm pretty sure only builds that I sign will be able to iCloud sync with the iOS port on the App Store.

Nothing hokey about it. I'm just a developer who believes in not asking too much of others when I put a Pull Request in. It's time for this stuff, though, so I'll get it done... soon-ish. ;-)

**Comment by syberknight** [comment]
okay, great!  how can i get a notification for when there are updates or if you switch it back over to the other account?
thanks.

**Comment by Ducasse** [comment]
Hi 
I'm a big fan of flycut and use it constantly and I migrated to Mojave and now even after reboot I cannot get my pasted code back in any text editor. 
I have mojave 10.14.5 and flycut 1.8.2 I cannot select any item in the list.
