### ISSUE TITLE
Flycut & passwords

### ISSUE THREAD

**Issue by twei55** [TermiT/Flycut#2]
Hello,

thanks for this really useful tool. Although I have an issue or maybe more a feature request. 

I use KeePassX (www.keepassx.org/) for storing my passwords. For security reasons, it removes the password from the clipboard after a specified time.

When using Flycut all these passwords are now stored as plain text in the Flycut history. I would really like to exclude certain applications from being part of the history. Is there an easy way to achieve this?

Cheers,
Tobias

**Comment by shaharke** [comment]
Unfortunately this doesn't seem to work with 1Password. Is there a way to make it work? Another alternative is to allow to clear the clipboard after a configured period of time. It would make it a bit more secure.

**Comment by MarkJerde** [comment]
Hi shaharke.
1Password uses a different "pasteboard type" string than KeePassX. It's `com.agilebits.onepassword`. I think this feature is broken, but trivial to fix, anyway. See info in #127 if interested.

Other options:
- You can Option-Click the Flycut icon in your menu bar to disable and reenable Flycut if you want to to avoid seeing things for a period.
- If your passwords follow a pattern of being a combination of at least one of each: [uppercase, lowercase, number, symbol] and no spaces, you can use the setting to detect clippings of specified lengths that match that pattern to have Flycut ignore them.

Of course, neither of those options will be available if you are on the App Store version (1.5) since that is something like eight years old and can't be updated due to changing restrictions on App Store content.

Hope this helps,
Mark

**Comment by Enricoza** [comment]
Hi @MarkJerde 
It's been a while since the last time someone mentioned this issue with other password managers like 1password. But the fix, trivial or not, was unfortunately not made yet.
I also see someone tried to fix it with this PR #117 and it's been reported to be working, but it was not merged back in 2016 and now can't be merged due to some conflicts.

Is there a reason for this not to be fixed yet? Or was this just forgot? 

PS: I would also be happy to work to a PR if that would help speed up the process of releasing the fix.
