### ISSUE TITLE
Cloud-based clipboard across multiple computers with FlyCut

### ISSUE THREAD

**Issue by evliu** [TermiT/Flycut#23]
I love the current dropbox feature; to copy code from one work mac to another work mac, I tend to make sure only one copy is using it, since dropbox does versioning rather than append new clipboard content. Would there be a way to run it at the same time on multiple computers and make a sort of cloud clipboard? Maybe with iCloud or dropbox? I'm a rather new developer in the java web-app world, and have yet the opportunity to learn MacOSX and iOS programming (don't even know Objective-C). Thanks!!

**Comment by MarkJerde** [comment]
TermiT asked recently about adding iCloud support to Flycut, so this looks like the right place to hold the current discussion.  Hopefully it'll be something we can provide soon.

I found this project that uses 108 lines of code to provide effortless sync of NSUserDefaults to iCloud in a very clean looking manner.  Just add one line of code to initialize it and it adds two listeners, one for NSUserDefaults changes that it can send to iCloud and one for iCloud changes that it can send to NSUserDefaults.  Seems like the right choice for Flycut.  What do you think?

https://github.com/MugunthKumar/MKiCloudSync

Caveats / things to consider that I see are the iCloud key-value store limit of 1 MB total per user per app and 64-character limit on keys as well as ensuring the things are synchronized in an acceptably timely manner.

Thanks for any thoughts / comments / endorsements on this.
Mark

**Comment by TermiT** [comment]
hey, Mark, I think MKiCloudSync is a good choice. And we should be fine with iCloud restrictions.

**Comment by MarkJerde** [comment]
We have iCloud Sync!  :-)

Download here: https://github.com/MarkJerde/Flycut/releases/tag/v1.9-sync

MKiCloudSync turned out to not work, since it uses iCloud Key-Value which is only available for apps that are distributed via the App Store.  Flycut cannot distribute via the App Store due to the API used to synthesize Command-V for paste.  There is another iCloud option that doesn't require the App Store, however, known as CloudKit.  I expanded MKiCloudSync into my own, significantly different, library to meet our sync needs over CloudKit.

The corresponding iOS version will be up on the App Store soon, and it is really fun to see the clippings list update in real time on your phone and in the menu or bezel.  The proper MVC to make the iOS interface look slick allowed the desktop interface to also update dynamically as changes happen, eliminating the problem that if you open the bezel too quick after copying you would have to press down-up to see your clipping.

This release looks in yet another different Library location for your saved preferences, so you'll have to deal with that.  A load-from-file option would be handy to deal with this, but also isn't a frequently encountered situation.
