### ISSUE TITLE
double pasting? 

### ISSUE THREAD

**Issue by manischewitzbacon** [TermiT/Flycut#29]
not always, but once it starts I can't seem to get it to stop.   if I have "foo" in my clipboard history (not in 1st postion) and try to paste it, it will paste "foofoo"

restarting app or clearing history does not help.

**Comment by shiv19** [comment]
Flycut version 1.5
MacOS version 10.14.6

I'm having the double pasting issue too! "sticky bezel" does help. But it would be great to have this bug fixed.

**Comment by MarkJerde** [comment]
Hi shiv19,
Flycut 1.5 is the App Store version that must be 8 or 9 years out of date now. (It can’t be updated due to the APIs Flycut has to call to make a paste happen.) You can find the most recent version of Flycut here: https://github.com/MarkJerde/Flycut/releases/tag/1.9.2 Hopefully that will solve your problem. 

Mark

**Comment by shiv19** [comment]
With 1.9.2 
the preference "Menu selection pastes" doesn't seem to work for me.
I'll restart my laptop and report here if it fixes it for me.

**Comment by shiv19** [comment]
After a full restart, it is working perfectly fine. Thanks @MarkJerde  :)
