### ISSUE TITLE
Flycut dead?

### ISSUE THREAD

**Issue by rhettjay** [TermiT/Flycut#296]
The last [commit](https://github.com/TermiT/Flycut/commit/9bd2303e1ba7604ba9d9a23369e8b6802ce3431c) was well over two years ago. @TermiT do you have a recommendation for path forward or a replacement? I appreciate your contributions to open source and am hoping you'll have a recommendation for a replacement? Many of the tools are in this same situation (Clippy and Maccy for example) and others are behind a pay wall. Can we get a definitive answer as to whether this will be deprecated at some point?

**Comment by GAGennadii** [comment]
Two things: I don't have time to work on it, and I'm also kind of okay with the current state of the app in terms of functionality.

**Comment by TermiT** [comment]
Two things: I don't have time to work on it, and I'm also okay with the app's current functionality. I don't have a recommendation, as I use Flycut when I work on a Macbook. I'm pretty sure other people can recommend alternatives.

**Comment by twknab** [comment]
> The last [commit](https://github.com/TermiT/Flycut/commit/9bd2303e1ba7604ba9d9a23369e8b6802ce3431c) was well over two years ago. @TermiT do you have a recommendation for path forward or a replacement? I appreciate your contributions to open source and am hoping you'll have a recommendation for a replacement? Many of the tools are in this same situation (Clippy and Maccy for example) and others are behind a pay wall. Can we get a definitive answer as to whether this will be deprecated at some point?

Flycut works great. As does Maccy. Both apps function great for all basic needs. Also both respond to issues. It's a free and open source tool. If you don't care for them, perhaps using the clipboard the old fashioned way is your best option.

**Comment by MarkJerde** [comment]
I use Flycut all day long every day. It’s a key part of my workflow as a software developer, a component in my flow of paying the bills each month, and a muscle memory feature of how I use the computer for any task. So nope, it’s not dead. It just isn’t needy so it keeps working without changes. 

It’s also how I got started writing Mac and iOS software and if ever anybody found a bug or needed a feature they would be free to debug and fix or add it.

**Comment by MarkJerde** [comment]
Oh, and to answer the specific question if Flycut will ever be “deprecated”: 
That’s really a word that doesn’t make sense here. (But I’ll get into other details that might address your concerns in a moment.)

Deprecation would be if someone said “you should stop using this because it will go away in the future”. Flycut is open source software so it would be hard for it to “go away” by any action of any person, group, or company. I’ll still have my copy of the source code on GitHub and my computer, and many others will too. The Flycut source code has become something that is hard to go away. 

Another concern though, could be, “will Flycut ever stop working?” 🤷 I dunno. 😄 (dunno == don’t know, for any non-native English speakers, but fit better here for the complete lack of a clue it can convey. Pardon the slang) But if it stops working due to changes in macOS you can bet at least a few of us will find the time to dig into it because we depend on this tool. We just might not dig into it on the schedule that someone else wants, because we aren’t being paid to and have other things we have to do because we are getting paid to. (But the people who want a fix are free to dig into it too and we’d love their involvement.)

As to, will changes in macOS ever make it impossible to fix Flycut to keep working?… please don’t make me jinx myself by suggesting it won’t. 😄 It’s hard to say, but not something easy to expect or that I’d suggest worrying about, because every app out there for any purpose has the same possibility of that happening. 

Hope this helps,
Mark

**Comment by rhettjay** [comment]
@MarkJerde thank you for taking the time to craft a thoughtful response. Please forgive the poor use of words. The idea I was attempting to convey is instances where the code has grown stale and contributors/maintainers have lost interest. My question was not meant to reflect poorly on anyone so if I came across that way I apologize.

To my intended point, I think you and @TermiT answered my concern well enough. There's not interest to continue updating it because it works well enough as is. I fully agree, I'm merely looking to the future. As MacOS continues to move into the ARM realm I am concerned it will eventually break and wanted to gauge maintenance interest. My past experience has been that commit regularity and # of open issues serve as an informative proxy for how well maintained/secure any open-source project is. With that knowledge, given the last commit was some time ago and issues have tended to remain open I felt the need to ask what I felt was a fair, albeit blunt, question. I did not intend to cause offense.

Thank you again for the replies. Happy to get involved and join up if I run into issues with it.

**Comment by rhettjay** [comment]
@twknab, I hope your comment was meant slightly tongue in cheek. I think my thoughts above summarize my intent. I apologize again if that came across wrong. 

For context, (and because I think the community may benefit thereby) I sometimes forget not all communities on the platform handle issues similarly. For instance Flycut has [100+ issues open](https://github.com/TermiT/Flycut/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) many of which have been open for over a year. Taken as a quick litmus test, my impression was the software is dead or at least dying. Upon deeper inspection however, many of those issues have answers. Thus, I again admit I was wrong in my initial assessment (further supported by the responses above). 

I might therefore suggest that it's a little in poor taste to insinuate that I don't care for the solution. 
> If you don't care for them, perhaps using the clipboard the old fashioned way is your best option.

I asked because I do care. Your comment leaves me with a bitter taste of the community (which I admittedly in part owe to my own first poor choice of written tone). Happy to continue the dialogue elsewhere if there might be benefit to continuing Flycut community. If not, I consider my issue resolved. Thank you all!

**Comment by twknab** [comment]
@rhettjay You mentioned "all the apps" as being somehow dead. I don't understand this assessment. Perhaps the metrics you have mentioned show the blind spots in these sorts of assessments. This assumes the software creator and users are not involved or aware of issues. In fact, these authors and users are aware. They utilize software which is essentially steady state. What new features must be added? The feature set is rich and functional. Not all software has to continue to evolve forward with new features. Sometimes a hammer is great as a hammer--and a hammer is timeless in its application and function. The metaphors to conceptualize software may not always reflect the reality.

These apps also function fine on Apple Silicon and work great. When they break, the community will respond. In fact, I've never had them so much as crash, which is testament to their craftsmanship. 

This expectation of yours may sound good in theory but is not reflective of the truth of software. Some software is good as it is, and can "just be" for a long while. There are other priorities, and these features work and continue to work well.

That being said, glad you appreciate the value of these very amazing clipboard utilities. They are a blessing to any workflow.

**Comment by MarkJerde** [comment]
@rhettjay Not so much a lack of "interest" in making changes to Flycut. Just a lack of need. Some software will be an ever changing attempt to add every feature just because it can be done. The emacs text editor remains the butt of all software engineering jokes for this, because who wouldn't want to check their email and do gosh knows what else in their text editor? 😆 

It may take some digging to find, perhaps because none of us have ever bothered to write an "ethos.md" file for Flycut, but in the GitHub issues there are discussions and statements that Flycut will strongly avoid feature creep. So it's a done deal that Flycut isn't going to just change for change sake or because someone has a neat idea. 99% of neat ideas that could be added to Flycut would just as well stand as an independent tool, so clean simplicity is protected by letting other tools do the other things.

As to the litmus test for project health. It sounds like a reasonable metric at the point of conception, and may perform well on some projects. I suppose examples could be found where it provides false positives and false negatives. I wouldn't assume the metric to, on average, be more successful or be less successful. There's just a lot of possibility out there and someone working on a software engineering masters or PhD can spend the time to quantify and tune such a thing.

I think we in this thread have found that the metric doesn't apply accurately to Flycut. One reason for this being, as you identified, we tend not to close out issues. Personally, I don't find it to be my place to shut down the conversation as this isn't a GitHub.com/Me/... project. Others who have access to close conversations might similarly feel they don't need to shut others out, or just don't have the time to spend on it. Surely there are pros and cons to the ways different teams use the GitHub tools. I haven't heard a reason to think that shutting down topics started by others is a necessary thing, so I'm kind of happy that Flycut failed the metric in that regard. 🙂 Hopefully we just politely respond our disagreement and leave the door (and issue) open.

Apple moved to ARM quite a bit ago now, at least in terms of the machines that we are using as Apple platform developers who need to be able to ensure compatibility of our day job apps, so I don't see any danger looming that would put Flycut's long term viability at risk.

Hope this helps,
Mark

**Comment by rhettjay** [comment]
@MarkJerde definitely, thanks for the thoughtful feedback.
