### ISSUE TITLE
Fixed clipboard items

### ISSUE THREAD

**Issue by jimbrechts** [TermiT/Flycut#75]
Imho, it would be handy to have some fixed clipboard items.
How I see it would work.
You can "favorite" them from the dropdown in the menu-bar. (or un-favorite them)
when you press the hotkey + arrow-down it cycles through the clipboard items, arrow-up through the favorite items.

I have some things I paste on regular base (account-number, tax-account number, etc...)
Having them shorthanded would be interesting..

**Comment by MarkJerde** [comment]
At a quick glance in the code, something like this may be possible by having two instances of the clippingStore.  It could take some work to make it capable of having two different instances coexist.

How does the user experience below sound?
User wants to add a clipping from the normal FlyCut clipboard to the favorites. -> User presses "F" while that clipping is displayed in the bezel.  The clipping is removed from the normal store and added to the favorites.
User wants to access favorites. -> User activates the bezel as normal, presses "f" to access the favorites.  All bezel functionality remains the same as with the normal store, but with the favorites store.  When the bezel closes, FlyCut automatically switches back to the normal store.

Example, if the user kept a small, unchanging set of favorites and FlyCut does not move the pasted favorite to the "most recent" position, and the user keeps their tax-account number at position three in the favorites: User presses shift-command-v to activate the bezel, "f" to switch to favorites, "3" to skip to the third position, and "return" to paste.

The approach of using a key to switch stores should be easier to implement than an approach to place the two stores adjacent in the bezel (arrow-up for favorites) because the code is already written to handle "down-arrow for next less recent entry"-type usage and would have to be reversed if the favorites store was "up arrow for next less recent entry".  Keeping track of the current direction of navigation and switching point between stores would be complicated.

**Comment by MarkJerde** [comment]
Here's a beta with a secondary fixed clipboard.  If you have any feedback I can try to make adjustments before I submit a patch for this to TermiT.

https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-FavoritesBeta.zip

Flycut as of 2014.07.02 with added feature of a secondary 'favorites' clipping store.  From bezel, press 'f' to switch between regular and favorites or press 'F' to move something from the regular to the favorites.  Bezel currently changes to yellowish when in the favorites to make it easy to distinguish.  Limit for number of items in the favorites is configurable in preferences.
