### ISSUE TITLE
where are the clips installed and the format of storage file?

### ISSUE THREAD

**Issue by redguardtoo** [TermiT/Flycut#82]
I'm developed some open sourced Emacs lisp plugin which could support your plugin.

**Comment by MarkJerde** [comment]
Hi Chen,
Preferences and clippings are stored in ~/Library/Application Support/Flycut/com.generalarcade.flycut.plist. The format is XML. 
- Mark

**Comment by redguardtoo** [comment]
cool.

**Comment by redguardtoo** [comment]
I released my plugin at https://github.com/redguardtoo/cliphist

Maybe you can claim Flycut is the first Emacs friendly clipboard manager on OS X, ; )

**Comment by redguardtoo** [comment]
Hi, as some user reported the the path and format is changed? Could you double check?
If that user were not using the latest version of flycut, I would ask him to upgrade.

**Comment by MarkJerde** [comment]
Take a look at #119.

**Comment by redguardtoo** [comment]
Did format change?

**Comment by MarkJerde** [comment]
Not knowing when you are wondering about change since, it's hard to say exactly, but having worked on Flycut for many years I can say that there has been no fundamental change to the saved preferences / clippings format. Fields have been added in some records that could foul up a sufficiently primitive home-grown parser, but those are not a change in format. Apple has long practiced a standard of encoding plist files in either xml1 or binary1, generally tending toward binary1, so perhaps you need to use plutil to convert it to a human-readable encoding?

**Comment by redguardtoo** [comment]
@MarkJerde , Thank you for the heads up.

Currently I use hard coded path for the history files. Can I use some environment variable to detect the history path?

My problem is I use regular expression to analyze the history, looks I should use xml api instead. Can you send me a simple latest history file? I'm using an old Mac without enough space to install XCode.
