### ISSUE TITLE
Greek Letters

### ISSUE THREAD

**Issue by novikyuval** [TermiT/Flycut#86]
Flycut does not work with greek letters, instead pasting a space. Example from Word in the screenshot.
<img width="599" src="https://cloud.githubusercontent.com/assets/14896464/10177750/7f0c5356-6704-11e5-908b-dfede9d78669.png">

**Comment by MarkJerde** [comment]
This is a test of ß in a copied sentence.

![screen shot 2015-10-02 at 11 21 03 pm](https://cloud.githubusercontent.com/assets/903956/10261427/71d1b8d4-695c-11e5-9c79-65a885aa4eaa.png)

Pasted via bezel after becoming a history item (rather than current clipping):  This is a test of ß in a copied sentence.

This test was using the option-s key combo for the beta character.  It worked fine on a build of the most recent Flycut code.  Could you test copying the beta in this response to make sure it isn't different from yours?  If my beta works and yours doesn't please reply with the beta character you are using so I can copy and test with it.

If you cannot get your Flycut to work with the beta in the first line of this response, you can try a build of the most recent Flycut code here: https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-2015.09.08.zip?raw=true

Thanks,
Mark

**Comment by novikyuval** [comment]
Hi,

In the example sentence you wrote it is not the greek letter beta, rather
the German letter Eszett.
I tried copying the letter from Wikipedia
<https://en.wikipedia.org/wiki/Beta>, which seemed to work, so I presumet
it might have to do with encoding.
It appears when using beta in Office Word, as was the case in my first
example.
Here it is again:


​This is still with version 1.5 of Flycut, I will only have time to install
the newest build later this week.

Thanks,
Yuval Novik

**Comment by MarkJerde** [comment]
I couldn't see anything in the space immediately following "Here it is again:" in your post.  Here's my try at copying from the beginning of the Wikipedia article you linked and pasting via the Flycut bezel.  Best of luck!

Beta (UK /ˈbiːtə/ or US /ˈbeɪtə/; uppercase Β, lowercase β, or cursive ϐ; Ancient Greek: βῆτα bḗta or Modern Greek: βήτα víta) is the second letter of the Greek alphabet.
