### ISSUE TITLE
Make FlyCut work with menu bar apps

### ISSUE THREAD

**Issue by JoelStickney** [TermiT/Flycut#93]
Things like Fantastical / NoteFile or any other app that doesn't have a Dock icon. FlyCut doesn't 'switch back' to these kinds of apps automatically when pasting because they don't follow the standard front window mentality (given they don't have a Dock icon nor a title at the top left) so there has to be a way to keep the front window active while cycling through the FlyCut menu (or switch back to the previous frontmost window despite it not following proper conventions).

**Comment by MarkJerde** [comment]
Hi @JoelStickney - I commented this on another issue you had contributed to, but since it's relevant to this one of yours I'm posting it here for you and anybody else in your situation as well.

 I just put in a fix for #45 that was suggested by another contributor which seems like a possible candidate for fixing this issue as well.

If you could try the beta to see if it fixes your problem I would really appreciated it.  You can download it from [https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-Issue45-Beta.tgz?raw=true](https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-Issue45-Beta.tgz?raw=true).  This build uses the Flycut preferences/save in ~/Library/Preferences/com.generalarcade.flycut.plist (this moves around depending on code-signing settings, so documented here so you don't have trouble losing your clippings list).

Thanks,
Mark

**Comment by JoelStickney** [comment]
It's definitely in the right direction - handling window management in the same way Quicksilver or Alfred does is the solution. But, I think there's a piece missing because it's still deactivating the frontmost window whenever the FlyCut modal pops up. That is really odd though, because Quicksilver doesn't and I know you're using the same methodology. That's why I'm guessing there must be something missing from those three lines of code.

**Comment by JoelStickney** [comment]
Latest build works :).

**Comment by swrobel** [comment]
@JoelStickney latest build where?

**Comment by JoelStickney** [comment]
Built from source. Developer will be releasing it soon.
